# Generated by Django 4.2.14 on 2024-09-14 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pong_game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='is_tournament_game',
            new_name='is_single_game',
        ),
        migrations.RemoveField(
            model_name='game',
            name='round',
        ),
        migrations.RemoveField(
            model_name='game',
            name='tournament',
        ),
        migrations.AddField(
            model_name='game',
            name='player2_alias',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='player2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games_as_player2', to=settings.AUTH_USER_MODEL),
        ),
    ]
