{
 "title": "Vault",
 "description": " Hashicorp Vault Metrics",
 "tags": [ "vault" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Host:",
    "query": "label_values(up{job=\"vault\"}, instance)"
   },
   {
    "name": "port",
    "query": "label_values(up{job=\"vault\",instance=~\"$node:(.*)\"}, instance)"
   },
   {
    "name": "mountpoint",
    "label": "Mount Point:",
    "query": "label_values(vault_secret_kv_count, mount_point)"
   }
  ]
 },
 "panels": [
  {
   "title": "Healthy Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Misc" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "up{job=\"vault\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Sealed Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "max(1 + vault_core_unsealed{})", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "Number of Leases",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(vault_expire_num_leases)" }
   ]
  }
 ]
}