groups:
  - name: vault
    rules:
      - alert: VaultDownORSealed
        expr: up{job="vault"} == 0
        for: 5s
        labels:
          severity: critical
        annotations:
          summary: "Vault is down or sealed"
          description: "Vault has been unreachable for more than 5 seconds."
  
  - name: django
    rules:
      - alert: DjangoIsDown
        expr: up{job="python"} == 0
        for: 5s
        labels:
          severity: critical
        annotations:
          summary: "Django is down"
          description: "Django has not processed any HTTP requests in the last 5 seconds."

  - name: postgresql
    rules:
      - alert: PostgresIsDown
        expr: pg_up == 0
        for: 5s
        labels:
          severity: critical
        annotations:
          summary: "PostgreSQL is down"
          description: "Il PostgreSQL has been unreachable for more than 5 seconds."
        
      - alert: PostgresExporterDown
        expr: up{job="postgres-exporter"} == 0
        for: 5s
        labels:
          severity: critical
        annotations:
          summary: "Postgres Exporter is down"
          description: "Il Postgres Exporter has been unreachable for more than 5 seconds."

  - name: nginx
    rules:
      - alert: NginxIsDown
        expr: nginx_up == 0
        for: 5s
        labels:
          severity: critical
        annotations:
          summary: "Nginx is down"
          description: "Nginx has been unreachable for more than 5 seconds."

      - alert: NginxExporterDown
        expr: up{job="nginx-exporter"} == 0
        for: 5s
        labels:
          severity: critical
        annotations:
          summary: "Nginx Exporter is down"
          description: "Nginx Exporter has been unreachable for more than 5 seconds."

