tls_server_config:
  cert_file: "/tls/certs/postgres-exporter.crt"
  key_file: "/tls/private/postgres-exporter.key"
  client_auth_type: "RequireAndVerifyClientCert"
  client_ca_file: "/tls/certs/ca.crt"
  client_allowed_sans: ["10.0.1.2","10.0.3.1"]
